sudo: false
language: rust

install:
  - "script/bootstrap"
  
script:
  - "script/cibuild"

after_script:
  - "script/after_cibuild"

rust:
  - nightly

env:
  - GTK=3.4
  - GTK=3.18

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - texinfo
      - graphviz
      - libgtk-3-dev

notifications:
  email:
    on_success: never
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#xtensis-editor"
    nick: xtensis-travis
    on_success: never
    on_failure: always
    use_notice: true
    skip_join: false
