#!/bin/bash

set -euo pipefail

export PATH="$HOME/.local/bin:$PATH"

# Run the `check` Makefile target
echo "INFO: Building and testing.."
make ci-check

# echo "INFO: Building docs.."
# make doc

exit
